// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: rag_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UseGraph      bool                   `protobuf:"varint,3,opt,name=use_graph,json=useGraph,proto3" json:"use_graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_rag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{0}
}

func (x *AskRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AskRequest) GetUseGraph() bool {
	if x != nil {
		return x.UseGraph
	}
	return false
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerDelta   string                 `protobuf:"bytes,1,opt,name=answer_delta,json=answerDelta,proto3" json:"answer_delta,omitempty"`
	ThinkingLog   string                 `protobuf:"bytes,2,opt,name=thinking_log,json=thinkingLog,proto3" json:"thinking_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_rag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{1}
}

func (x *AskResponse) GetAnswerDelta() string {
	if x != nil {
		return x.AnswerDelta
	}
	return ""
}

func (x *AskResponse) GetThinkingLog() string {
	if x != nil {
		return x.ThinkingLog
	}
	return ""
}

type EmbedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*EmbedRequest_Text
	//	*EmbedRequest_ImageUrl
	Data          isEmbedRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_rag_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedRequest) GetData() isEmbedRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		if x, ok := x.Data.(*EmbedRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *EmbedRequest) GetImageUrl() string {
	if x != nil {
		if x, ok := x.Data.(*EmbedRequest_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return ""
}

type isEmbedRequest_Data interface {
	isEmbedRequest_Data()
}

type EmbedRequest_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type EmbedRequest_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

func (*EmbedRequest_Text) isEmbedRequest_Data() {}

func (*EmbedRequest_ImageUrl) isEmbedRequest_Data() {}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_rag_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

// 🔥 新增请求：直接传文件内容的字节流
type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_rag_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{4}
}

func (x *ParseRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ParseRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// 🔥 新增响应：返回多个切片，每个切片都有文本和向量
type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*DocChunk            `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_rag_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{5}
}

func (x *ParseResponse) GetChunks() []*DocChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type DocChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                          // 切分后的文本片段
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`                   // 该片段对应的 384维 向量
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"` // 页码 (用于前端跳转)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocChunk) Reset() {
	*x = DocChunk{}
	mi := &file_rag_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocChunk) ProtoMessage() {}

func (x *DocChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocChunk.ProtoReflect.Descriptor instead.
func (*DocChunk) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{6}
}

func (x *DocChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocChunk) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *DocChunk) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

var File_rag_service_proto protoreflect.FileDescriptor

const file_rag_service_proto_rawDesc = "" +
	"\n" +
	"\x11rag_service.proto\x12\x06rag.v1\"^\n" +
	"\n" +
	"AskRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuse_graph\x18\x03 \x01(\bR\buseGraph\"S\n" +
	"\vAskResponse\x12!\n" +
	"\fanswer_delta\x18\x01 \x01(\tR\vanswerDelta\x12!\n" +
	"\fthinking_log\x18\x02 \x01(\tR\vthinkingLog\"K\n" +
	"\fEmbedRequest\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x1d\n" +
	"\timage_url\x18\x02 \x01(\tH\x00R\bimageUrlB\x06\n" +
	"\x04data\"'\n" +
	"\rEmbedResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\"N\n" +
	"\fParseRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"9\n" +
	"\rParseResponse\x12(\n" +
	"\x06chunks\x18\x01 \x03(\v2\x10.rag.v1.DocChunkR\x06chunks\"]\n" +
	"\bDocChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber2\xbc\x01\n" +
	"\n" +
	"LLMService\x126\n" +
	"\tAskStream\x12\x12.rag.v1.AskRequest\x1a\x13.rag.v1.AskResponse0\x01\x128\n" +
	"\tEmbedData\x12\x14.rag.v1.EmbedRequest\x1a\x15.rag.v1.EmbedResponse\x12<\n" +
	"\rParseAndEmbed\x12\x14.rag.v1.ParseRequest\x1a\x15.rag.v1.ParseResponseB\x1bZ\x19Chimera-RAG/api/rag/v1;v1b\x06proto3"

var (
	file_rag_service_proto_rawDescOnce sync.Once
	file_rag_service_proto_rawDescData []byte
)

func file_rag_service_proto_rawDescGZIP() []byte {
	file_rag_service_proto_rawDescOnce.Do(func() {
		file_rag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)))
	})
	return file_rag_service_proto_rawDescData
}

var file_rag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rag_service_proto_goTypes = []any{
	(*AskRequest)(nil),    // 0: rag.v1.AskRequest
	(*AskResponse)(nil),   // 1: rag.v1.AskResponse
	(*EmbedRequest)(nil),  // 2: rag.v1.EmbedRequest
	(*EmbedResponse)(nil), // 3: rag.v1.EmbedResponse
	(*ParseRequest)(nil),  // 4: rag.v1.ParseRequest
	(*ParseResponse)(nil), // 5: rag.v1.ParseResponse
	(*DocChunk)(nil),      // 6: rag.v1.DocChunk
}
var file_rag_service_proto_depIdxs = []int32{
	6, // 0: rag.v1.ParseResponse.chunks:type_name -> rag.v1.DocChunk
	0, // 1: rag.v1.LLMService.AskStream:input_type -> rag.v1.AskRequest
	2, // 2: rag.v1.LLMService.EmbedData:input_type -> rag.v1.EmbedRequest
	4, // 3: rag.v1.LLMService.ParseAndEmbed:input_type -> rag.v1.ParseRequest
	1, // 4: rag.v1.LLMService.AskStream:output_type -> rag.v1.AskResponse
	3, // 5: rag.v1.LLMService.EmbedData:output_type -> rag.v1.EmbedResponse
	5, // 6: rag.v1.LLMService.ParseAndEmbed:output_type -> rag.v1.ParseResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rag_service_proto_init() }
func file_rag_service_proto_init() {
	if File_rag_service_proto != nil {
		return
	}
	file_rag_service_proto_msgTypes[2].OneofWrappers = []any{
		(*EmbedRequest_Text)(nil),
		(*EmbedRequest_ImageUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_service_proto_goTypes,
		DependencyIndexes: file_rag_service_proto_depIdxs,
		MessageInfos:      file_rag_service_proto_msgTypes,
	}.Build()
	File_rag_service_proto = out.File
	file_rag_service_proto_goTypes = nil
	file_rag_service_proto_depIdxs = nil
}
