# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rag_service.proto\x12\x06rag.v1\"z\n\nAskRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x12\n\nuse_search\x18\x04 \x01(\x08\x12\x11\n\tuse_graph\x18\x05 \x01(\x08\x12\x11\n\timage_url\x18\x06 \x01(\t\"a\n\x0b\x41skResponse\x12\x14\n\x0c\x61nswer_delta\x18\x01 \x01(\t\x12\x14\n\x0cthinking_log\x18\x02 \x01(\t\x12&\n\x0bsource_docs\x18\x03 \x03(\x0b\x32\x11.rag.v1.Reference\">\n\tReference\x12\x10\n\x08\x64oc_name\x18\x01 \x01(\t\x12\x10\n\x08page_num\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\";\n\x0c\x45mbedRequest\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\x13\n\timage_url\x18\x02 \x01(\tH\x00\x42\x06\n\x04\x64\x61ta\"\x1f\n\rEmbedResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32~\n\nLLMService\x12\x36\n\tAskStream\x12\x12.rag.v1.AskRequest\x1a\x13.rag.v1.AskResponse0\x01\x12\x38\n\tEmbedData\x12\x14.rag.v1.EmbedRequest\x1a\x15.rag.v1.EmbedResponseB\x12Z\x10\x61pi/rag/v1;ragv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020api/rag/v1;ragv1'
  _globals['_ASKREQUEST']._serialized_start=29
  _globals['_ASKREQUEST']._serialized_end=151
  _globals['_ASKRESPONSE']._serialized_start=153
  _globals['_ASKRESPONSE']._serialized_end=250
  _globals['_REFERENCE']._serialized_start=252
  _globals['_REFERENCE']._serialized_end=314
  _globals['_EMBEDREQUEST']._serialized_start=316
  _globals['_EMBEDREQUEST']._serialized_end=375
  _globals['_EMBEDRESPONSE']._serialized_start=377
  _globals['_EMBEDRESPONSE']._serialized_end=408
  _globals['_LLMSERVICE']._serialized_start=410
  _globals['_LLMSERVICE']._serialized_end=536
# @@protoc_insertion_point(module_scope)
