# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rag_service_pb2 as rag__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskStream = channel.unary_stream(
                '/rag.v1.LLMService/AskStream',
                request_serializer=rag__service__pb2.AskRequest.SerializeToString,
                response_deserializer=rag__service__pb2.AskResponse.FromString,
                _registered_method=True)
        self.EmbedData = channel.unary_unary(
                '/rag.v1.LLMService/EmbedData',
                request_serializer=rag__service__pb2.EmbedRequest.SerializeToString,
                response_deserializer=rag__service__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.ParseAndEmbed = channel.unary_unary(
                '/rag.v1.LLMService/ParseAndEmbed',
                request_serializer=rag__service__pb2.ParseRequest.SerializeToString,
                response_deserializer=rag__service__pb2.ParseResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseAndEmbed(self, request, context):
        """🔥 新增：解析并向量化 PDF
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AskStream,
                    request_deserializer=rag__service__pb2.AskRequest.FromString,
                    response_serializer=rag__service__pb2.AskResponse.SerializeToString,
            ),
            'EmbedData': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedData,
                    request_deserializer=rag__service__pb2.EmbedRequest.FromString,
                    response_serializer=rag__service__pb2.EmbedResponse.SerializeToString,
            ),
            'ParseAndEmbed': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseAndEmbed,
                    request_deserializer=rag__service__pb2.ParseRequest.FromString,
                    response_serializer=rag__service__pb2.ParseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.v1.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.v1.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.v1.LLMService/AskStream',
            rag__service__pb2.AskRequest.SerializeToString,
            rag__service__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.LLMService/EmbedData',
            rag__service__pb2.EmbedRequest.SerializeToString,
            rag__service__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseAndEmbed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.LLMService/ParseAndEmbed',
            rag__service__pb2.ParseRequest.SerializeToString,
            rag__service__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
